### ISSUE TITLE
Getting a Syntax Error: Expected $, found @

### ISSUE THREAD

**Issue by gregpalios** [IlyaMatsuev/Apex-GraphQL-Client#29]
### Summary

I am trying to implement a mutation that creates a token using an email and password combination in the variables. I am receiving this error: `First error: Syntax Error GraphQL (1:37) Expected $, found @` in reference to the `@` in the email being passed.

### Steps To Reproduce:

1. Created the code using this structure:

` GraphQLField tokenCreateNode = new GraphQLField('tokenCreate')
            // Point the argument to the variables
            .withArgument('email', '$email')
            .withArgument('password', '$password')
            .withField('token')
            .withField('refreshToken');

GraphQLMutation mutation = new GraphQLMutation('CreateToken', tokenCreateNode)
            // Define variable for the mutation
            .defineVariable('email', email)
            .defineVariable('password', password);`

### Expected result

Successful callout

### Actual result

Getting syntax error

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by IlyaMatsuev** [comment]
Thanks for submitting the issue. I'll take a look at the example above as soon as I can

**Comment by gregpalios** [comment]
For extra context, this is the mutation query I am trying to post:

`mutation CreateToken($email: String!, $password: String!) {
  tokenCreate(email: $email, password: $password) {
    token
    refreshToken
    errors {
      message
      field
    }
    user {
      id
      isVet
      firstName
      lastName
      email
    }
  }
}
`
Variables:

`{
	"email": "ivincent@chewy.com",
	"password": "PracticeHubSalesforceAPI2023!"
}`

**Comment by IlyaMatsuev** [comment]
@gregpalios I see that you're trying to define two variables in the mutation `email` and `password`, but when you define variables you need to specify: 1) its name; 2) its type
In the example above you're trying to put email and password values directly into `defineVariable` method, which is not correct. According to the GraphQL request that you shared today, it should look something like this:

```java
GraphQLField tokenCreateNode = new GraphQLField('tokenCreate')
  // Point the argument to the variables
  .withArgument('email', '$email')
  .withArgument('password', '$password')
  .withField('token')
  .withField('refreshToken');

GraphQLMutation mutation = new GraphQLMutation('CreateToken', tokenCreateNode)
  // Define variable for the mutation
  .defineVariable('email', 'String!')    // <-- Here you specify the name and the type of your variable
  .defineVariable('password', 'String!');

// Then, when you create a request, you can actually pass the values for your variables
GraphQLRequest request = mutation.asRequest()
  .withVariable('password', password)
  .withVariable('email', email);
```

You can take a look at the example here: https://github.com/IlyaMatsuev/Apex-GraphQL-Client/blob/main/docs/examples/send-mutation.apex

Or in the documentation for the `defineVariable` method: https://github.com/IlyaMatsuev/Apex-GraphQL-Client/tree/main/docs/types#methods-5

Why couldn't we allow to provide the value of the variable directly when you define it?
- The reason is that this is how GraphQL works - before using variables in the query/mutation, you have to specify what type that variable has. The values to variables are actually assigned only when you make an HTTP request, that's why you can only provide values to your variables when you create `GraphQLRequest`
- Alternatively, you can just use simple arguments with no variables, then your request would look something like this:

```gql
mutation CreateToken {
  tokenCreate(email: 'test@test.com', password: 'testpassword') {
    token
    refreshToken
    errors {
      message
      field
    }
    user {
      id
      isVet
      firstName
      lastName
      email
    }
  }
} 
```


Please let me know if that helped or not

**Comment by gregpalios** [comment]
@IlyaMatsuev That worked! thank you.

I am now trying to do a slightly more complex call, which looks like this:

`mutation AdminStaffCreate($schemaName: String!, $email: String!, $firstName: String!, $lastName: String!) {
    staffUpdateOrCreate(input: {
        groups: [CLINIC_STAFF, CLINIC_ADMINISTRATOR],
        email: $email,
        firstName: $firstName,
        lastName: $lastName,
        isActive: true
    },
    schemaName: $schemaName
    ) {
        id
        firstName
        lastName
        email  
       
    }
}`

The input.group argument takes an ENUM type. I can't figure out how to send this.

**Comment by IlyaMatsuev** [comment]
@gregpalios
This is an interesting case... I haven't tried to send an array of enums as arguments before in my test scenarios

It is for sure possible to send a single argument as a enum value but not for an array - https://github.com/IlyaMatsuev/Apex-GraphQL-Client/blob/main/CHANGELOG.md#enum-arguments

But honestly, that GraphQL request doesn't look optimized to my mind. What I would do in your place is create an input type for the stuff entity on your server (if you have access to it):

```gql
input CreateStaffInput {
  groups: [ClinicGroupEnum!]!     # <-- your enum type here
  email: String!
  firstName: String!
  lastName: String!
}
```

Then your request would look something like this:

```gql
mutation AdminStaffCreate($schemaName: String!, $staff: CreateStaffInput!) {
  staffUpdateOrCreate(input: $staff, schemaName: $schemaName) {
    id
    firstName
    lastName
    email
  }
}
```

To do that request in Apex you would need to create a class that would describe that `CreateStaffInput` entity:

```java
class CreateStaffInput {
  public String email;
  public String firstName;
  public String lastName;
  public List<String> groups;     // <-- Here I suppose you can just use the list of strings

  public CreateStaffInput(String email, String firstName, String lastName) {
    this.email = email;
    this.firstName = firstName;
    this.lastName = lastName;
    this.groups = new List<String> { 'CLINIC_STAFF', 'CLINIC_ADMINISTRATOR' };
  }
}
```

Then, when you create a `GraphQLRequest` you should be able to use `withVariable` method to add an instance of your input to the variable:

```java
// ... Create GraphQLMutation with defined variables ...

CreateStaffInput staff = new CreateStaffInput('test@test.com', 'Bob', 'Marley');

GraphQLRequest request = mutation.asRequest()
  .withVariable('staff', staff)    // <-- This should theoretically serialize the object into JSON and on the server side strings should be parsed as enums without any issues (I assume :) )
  .withVariable('schemaName', 'someSchemaName');
```

Try to send this request and let me know if it works. If this workaround doesn't help I will try to make it possible to specify argument values as arrays of enums

**Comment by IlyaMatsuev** [comment]
@gregpalios 
I will close this issue for now because the problem that was originally described is not relevant anymore. However, feel free to follow up on the discussion here.

For future reference:
- if you have more question regarding the usage of the library, please create a new discussion here -> https://github.com/IlyaMatsuev/Apex-GraphQL-Client/discussions
- if you find a bug or you want to request a new feature (like the one above, that would allow array enums as arguments) then please create a separate story

Thanks

**Comment by gregpalios** [comment]
That's ok, I will do things manually to avoid the enum headache for now. Thanks for your help, I have both callouts working now. This is a great tool, glad I found it!

**Comment by IlyaMatsuev** [comment]
@gregpalios
FYI: I'll deliver a 2.1 release in a couple of days (or something around that) that will bring an ability to provide an array of enums in a query. You can check the PR linked above
