### ISSUE TITLE
I can't seem to be able to install the package in my sandbox

### ISSUE THREAD

**Issue by adelazalewski** [IlyaMatsuev/Apex-GraphQL-Client#8]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1. Clicked the install in sandbox link form your readme
1.  This is step 2. Clicked install for admins only, but al lit does is running and saying looking for admins and them error when it times out because the run time is took too long 

### Expected result
Expected it not to take so long to install and time out ..

### Actual result
got an email that let me know the installation of the package failed

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by IlyaMatsuev** [comment]
Hey
Thanks for letting me know about this
I'll look into it

**Comment by adelazalewski** [comment]
thanks so much

**Comment by IlyaMatsuev** [comment]
@adelazalewski 
I've just tried to replicate this one but I was able to successfully install the package via readme links (in sandbox and dev org as well)
Did you try to install it again? Maybe there were some problems on the Sf side at that time

**Comment by adelazalewski** [comment]
Ok, thanks for getting back to me. ill try again right now

**Comment by adelazalewski** [comment]
nop. I can't install it in the sandbox i want. Maybe is the sandbox...idk

**Comment by IlyaMatsuev** [comment]
@adelazalewski 
Can you share the exact error message/email?

**Comment by adelazalewski** [comment]
Problem:

1.  Apex compile failure
Apex class DocMagicService: line 11, column 22: Method does not exist or incorrect signature: void send(String) from the type DocMagicService.PostCreateLoanFromURLA

**Comment by adelazalewski** [comment]
and it says that if it still continues to fail to contact Salesforce CRM and provide the error above to them as well....

**Comment by IlyaMatsuev** [comment]
Okay, I see
There is no class named **DocMagicService** in this package. This class already exists in your sandbox.
The problem is that when you try to install the package Salesforce compiles all Apex on your sandbox. Therefore, it looks like you have some issues in your own code in **DocMagicService** class.

So, you have two options:
1. Fix this class and be sure it deploys to sandbox successfully and then install the package again.
2. Otherwise, during the package installation, click _Advanced Options_ and select _Compile only the Apex in the package_ as shown in the screenshot. It should help

<img width="1116" alt="Screenshot 2022-01-06 at 10 55 50 PM" src="https://user-images.githubusercontent.com/39780006/148457923-61e4d40f-d2d9-4f65-9c99-57825d81a391.png">

**Comment by adelazalewski** [comment]
thought so, thanks so much for taking the time to help me with this

**Comment by IlyaMatsuev** [comment]
You're welcome
